### ISSUE TITLE
关于RiseNumberTextView中fromNumber的设置问题

### ISSUE THREAD

**Issue by THEONE10211024** [litao0621/RiseNumber#1]
个人觉得RiseNumberTextView类中fromNumber的设计是不必要的，何不让数字直接从0增长？这样给用户的视觉体验更好

**Comment by litao0621** [comment]
当时是为了保持增长频率相似，不想出现比如100和100000这种跳动太大的问题，我现在没有太多时间来维护这些项目，如果你有兴趣我可以将你加入到Collaborators中，你可以更具自己想法来完善这个项目，如果对我的其他项目有兴趣，我也同样可以将你加入到Collaborators中，：）

**Comment by THEONE10211024** [comment]
我感觉这种跳动其实还好，至少是匀速变化的。加上了fromNumber会有一个跃变，给用户不流畅的体验。你要能把我加入Collaborators中，我很高兴！

**Comment by litao0621** [comment]
好了，你可以更具你的想法来完善，很高兴你能来维护这个项目 :smile:
